//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIZ.GUI {
    
    
    public partial class XemThongTinTaiKhoan {
        
        /// <summary>
        /// Catalogs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.catalogs Catalogs1;
        
        /// <summary>
        /// NewProduce1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.NewProduce NewProduce1;
        
        /// <summary>
        /// AdvertisementLeft1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.Advertisement AdvertisementLeft1;
        
        /// <summary>
        /// XemThongTinTaiKhoan1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.XemThongTinTaiKhoan XemThongTinTaiKhoan1;
        
        /// <summary>
        /// Login1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.Login Login1;
        
        /// <summary>
        /// Cart1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.Cart Cart1;
        
        /// <summary>
        /// Payment1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.Payment Payment1;
    }
}
