//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIZ.GUI.Shared {
    
    
    public partial class Default {
        
        /// <summary>
        /// Catalogs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.catalogs Catalogs1;
        
        /// <summary>
        /// CatalogManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.CatalogManager CatalogManager1;
        
        /// <summary>
        /// CatalogAdmin1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.CatalogAdmin CatalogAdmin1;
        
        /// <summary>
        /// NewProduce1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.NewProduce NewProduce1;
        
        /// <summary>
        /// TenNewProduce1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.TenNewProduce TenNewProduce1;
        
        /// <summary>
        /// NewModifyProduce1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.NewModifyProduce NewModifyProduce1;
        
        /// <summary>
        /// Login1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.Login Login1;
        
        /// <summary>
        /// Cart1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.Cart Cart1;
        
        /// <summary>
        /// AdvertisementLeft1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.Advertisement AdvertisementLeft1;
        
        /// <summary>
        /// Payment1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BIZ.GUI.UserControls.Payment Payment1;
    }
}
